"""empty message

Revision ID: 56eb0dddd7ee
Revises: 60b3fdb3496e
Create Date: 2021-07-20 16:54:00.403207

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '56eb0dddd7ee'
down_revision = '60b3fdb3496e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('disabled', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
